name: icme
channels:
  - defaults
dependencies:
  - pip
  - python
  - setuptools
  - pip:
    - pickle5
    - joblib
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - seaborn
    - statsmodels
    - tensorflow==2.5.0rc1
    - tensorflow-estimator==2.5.0rc0
    - tensorflow-probability==0.12.2
    - werkzeug
