name: icme
channels:
  - defaults
dependencies:
  - pickleshare
  - pip
  - python
  - setuptools
  - pip:
    - cloudpickle
    - joblib
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - seaborn
    - statsmodels
    - tensorflow
    - tensorflow-estimator
    - tensorflow-probability
    - werkzeug
